#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DVI-I-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 0
bspc config border_width         2
bspc config window_gap          10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xrandr --output DVI-I-0 --auto --left-of DP-0 --rotate right
exec bash ~/.config/bspwm/startup.sh
